version: '3'

services:
  spring-app:
    image: # kim588097/image:태그(이미지를 어떻게 해야하는지 모름:latest)
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:mysql://withus.c92sig4iwc48.ap-northeast-2.rds.amazonaws.com:3306/WITHUS
      SPRING_DATASOURCE_USERNAME: WITHUS
      SPRING_DATASOURCE_PASSWORD: 01050355253

    depends_on:
      - redis
    volumes:
      - C:\Users\alstj\Desktop\withUs\build\libs\withUs-0.0.1-SNAPSHOT:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always