version: '3'

services:
  spring-app:
    container_name: spring-app-withUs
    image: minseok588098/withus
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      SPRING_REDIS_HOST: redis-server-withUs
      SPRING_REDIS_PORT: 6379
      WEB_DB_URL: ${{ secrets.WEB_DB_URL }}
      WEB_DB_USERNAME: ${{ secrets.WEB_DB_USERNAME }}
      WEB_DB_PASSWORD: ${{ secrets.WEB_DB_PASSWORD }}
      S3_ACCESSKEY: ${{ secrets.S3_ACCESSKEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_REGION: ${{ secrets.S3_REGION }}
      S3_SECRETKEY: ${{ secrets.S3_SECRETKEY }}
      S3_STACK_AUTO: ${{ secrets.S3_STACK_AUTO }}

    depends_on:
      - redis

  redis:
    container_name: redis-server-withUs
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always