version: '3'

services:
  spring-app:
    container_name: spring-app-withUs
    image: minseok588098/withUs
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis-server-withUs
      SPRING_REDIS_PORT: 6379
      WEB_DB_URL: jdbc:mysql://withus.c92sig4iwc48.ap-northeast-2.rds.amazonaws.com:3306/WITHUS
      WEB_DB_USERNAME: WITHUS
      WEB_DB_PASSWORD: 01050355253
      S3_ACCESSKEY: AKIAYC4QB6WUYIRO2YTX
      S3_BUCKET_NAME: sparta-withus
      S3_REGION: ap-northeast-2
      S3_SECRETKEY: iAxUIlkkrdExoBjI1NZIp4XS3leKa4dGpw0bCgeK
      S3_STACK_AUTO: false

    depends_on:
      - redis

  redis:
    container_name: redis-server-withUs
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always